project_name: "HydroMassNet"
seed: 1601
target_column: "logMHI"

paths:
  raw_data: "data/hydromassnet_full_dataset_all_columns.csv"
  processed_data: "data/hydromassnet_processed.csv"

data_processing:
  features:
    - "iMAG"
    - "e_iMAG"
    - "logMsT"
    - "logSFR22"
    - "e_logMsT"
    - "Dist"
    - "RVel"
    - "Ag"
    - "Ai"
    - "surface_brightness_proxy"
