project_name: HydroMassNet
seed: 1601

paths:
  raw_data: data/hydromassnet_full_dataset_all_columns.csv
  processed_data: data/hydromassnet_processed.csv
  results: results
  feature_selection_results: results/feature_selection
  search_results: results/hyperparameter_search
  champion_results: results/champions
  log_file: logs/pipeline.log

data_processing:
  val_split: 0.15
  test_split: 0.15

target_column: logMHI

training:
  epochs: 300
  patience: 35
  enable_mixed_precision: true # Habilita/desabilita precisão mista

logging:
  level: INFO # Níveis: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

feature_selection:
  min_features: 5
  candidate_features:
    - iMAG
    - e_iMAG
    - logMsT
    - logSFR22
    - e_logMsT
    - Dist
    - RVel
    - Ag
    - Ai
    - surface_brightness_proxy
  evaluation_model_config:
    learning_rate: 0.001
    batch_size: 128
    layers: '64-32'
    dropout: 0.2
    features:
      - iMAG
      - e_iMAG
      - logMsT
      - logSFR22
      - e_logMsT
      - Dist
      - RVel
      - Ag
      - Ai
      - surface_brightness_proxy

hyperparameter_search:
  vanilla:
    features:
      - ['iMAG', 'e_iMAG', 'logMsT', 'logSFR22', 'e_logMsT']
    learning_rate: [0.001, 0.0005]
    batch_size: [64, 128, 256]
    layers: ['256-128', '128-64-32', '512-256-128']
    dropout: [0.1, 0.2, 0.3]
  bnn:
    features:
      - ['iMAG', 'e_iMAG', 'logMsT', 'logSFR22', 'e_logMsT']
    learning_rate: [0.001, 0.0005, 0.0001]
    batch_size: [128, 256]
    layers: ['128-64', '256-128', '256-128-64']
  dbnn:
    features:
      - ['iMAG', 'e_iMAG', 'logMsT', 'logSFR22', 'e_logMsT']
    learning_rate: [0.0005, 0.0001]
    batch_size: [256, 512]
    core_layers: ['256-128', '512-256', '512-256-128']
    head_layers: ['64', '32']