project_name: "HydroMassNet"
seed: 1601
target_column: "logMHI"

paths:
  raw_data: "data/hydromassnet_full_dataset_all_columns.csv"
  processed_data: "data/hydromassnet_processed.csv"
  saved_models: "results/saved_models/"
  plots: "results/plots/"
  search_results: "results/search_results/"

data_processing:
  val_split: 0.2
  test_split: 0.1
  features:
    [
      "iMAG",
      "e_iMAG",
      "logMsT",
      "logSFR22",
      "e_logMsT",
      "Dist",
      "RVel",
      "Ag",
      "Ai",
      "surface_brightness_proxy",
    ]

training:
  epochs: 500
  patience: 25

hyperparameter_search:
  bnn:
    learning_rate: [0.001, 0.0005]
    batch_size: [64, 128, 256]
    layers: ["128-64", "256-128"]
  dbnn:
    learning_rate: [0.001, 0.0005]
    batch_size: [64, 128, 256]
    core_layers: ["256-128", "512-256"]
    head_layers: ["64", "128-64"]
  vanilla:
    learning_rate: [0.001, 0.0005]
    batch_size: [64, 128, 256]
    layers: ["128-64", "256-128"]
    dropout: [0.1, 0.2, 0.3]

feature_selection:
  candidates:
    [
      "iMAG",
      "e_iMAG",
      "logMsT",
      "logSFR22",
      "e_logMsT",
      "Dist",
      "RVel",
      "Ag",
      "Ai",
      "surface_brightness_proxy",
    ]
  min_features: 4
  top_n_to_tune: 5

champion_models:
  bnn:
    features:
      [
        "iMAG",
        "e_iMAG",
        "logMsT",
        "logSFR22",
        "e_logMsT",
        "Dist",
        "RVel",
        "Ag",
        "Ai",
        "surface_brightness_proxy",
      ]
    learning_rate: 0.0005
    batch_size: 256
    layers: [10, 512, 256, 128, 1]
    save_name: "champion_bnn.weights.h5"
  dbnn:
    features:
      [
        "iMAG",
        "logMsT",
        "logSFR22",
        "e_logMsT",
        "Dist",
        "RVel",
        "Ag",
        "surface_brightness_proxy",
      ]
    learning_rate: 0.001
    batch_size: 256
    core_layers: [8, 512, 256]
    head_layers: [256, 128, 64, 1]
    save_name: "champion_dbnn.weights.h5"
  vanilla:
    features:
      [
        "iMAG",
        "e_iMAG",
        "logMsT",
        "logSFR22",
        "e_logMsT",
        "Dist",
        "RVel",
        "Ag",
        "Ai",
        "surface_brightness_proxy",
      ]
    learning_rate: 0.0005
    batch_size: 64
    layers: [10, 128, 64, 1]
    dropout: 0.2
    save_name: "champion_vanilla.weights.h5"
